version: '3.8'

services:
  app:
    image: automacaodebaixocusto/spark-course-unificado:latest
    environment:
      - JWT_SECRET=Q2h5b3VldG9zZWNyZXRzZXJhbGhhZG9yYWRvcmFuZG9tMTIzIT8kKiYoKS0r
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=community
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=131489152850082175195580
      - MINIO_ENDPOINT=mp.iacas.top
      - MINIO_PORT=443
      - MINIO_ACCESS_KEY=1013141255245882
      - MINIO_SECRET_KEY=5420658821784955
      - MINIO_USE_SSL=true
      - MINIO_REGION=us-east-1
      - MINIO_BUCKET=community
      - MINIO_PUBLIC_URL=https://mp.iacas.top

        # Upload Settings
      - MINIO_UPLOAD_TIMEOUT=300000
      - MINIO_MAX_FILE_SIZE=104857600
      - MINIO_RETENTION_DAYS=365
      
      # Stripe Configuration (Desabilitado - Configure suas chaves reais)
      - STRIPE_SECRET_KEY=sk_test_disabled_configure_real_key
      - STRIPE_WEBHOOK_SECRET=whsec_disabled_configure_real_secret
      - STRIPE_PUBLISHABLE_KEY=pk_test_disabled_configure_real_key
      
      # Mercado Pago Configuration (Configure seu token real)
      - MERCADOPAGO_ACCESS_TOKEN=TEST-12345678901234567890123456789012
      - MERCADOPAGO_WEBHOOK_URL=https://community.iacas.top/api/webhooks/mercadopago
      - MERCADOPAGO_SUCCESS_URL=https://community.iacas.top/payment/success
      - MERCADOPAGO_FAILURE_URL=https://community.iacas.top/payment/failure
      - MERCADOPAGO_PENDING_URL=https://community.iacas.top/payment/pending
    networks:
      - network_public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        # Frontend route
        - "traefik.http.routers.spark-course-frontend.rule=Host(`community.iacas.top`) && !PathPrefix(`/api`)"
        - "traefik.http.routers.spark-course-frontend.entrypoints=websecure"
        - "traefik.http.routers.spark-course-frontend.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.spark-course-frontend.loadbalancer.server.port=3001"
        # API route
        - "traefik.http.routers.spark-course-api.rule=Host(`community.iacas.top`) && PathPrefix(`/api`)"
        - "traefik.http.routers.spark-course-api.entrypoints=websecure"
        - "traefik.http.routers.spark-course-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.spark-course-api.loadbalancer.server.port=3001"
        - "traefik.docker.network=network_public"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  network_public:
    external: true
    name: network_public 