version: '3.8'

services:
  app:
    image: automacaodebaixocusto/spark-course-unificado:latest
    environment:
      - JWT_SECRET=um-segredo-bem-forte
      - POSTGRES_HOST=postgres_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nome_do_banco
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - MINIO_ENDPOINT=mp.iacas.top
      - MINIO_PORT=443
      - MINIO_ACCESS_KEY=1013141255245882
      - MINIO_SECRET_KEY=5420658821784955
      - MINIO_USE_SSL=true
      - MINIO_BUCKET=community
      - MINIO_PUBLIC_URL=https://mp.iacas.top
      - MINIO_REGION=us-east-1
    networks:
      - network_public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.spark-course.rule=Host(`community.iacas.top`) && !PathPrefix(`/api`)"
        - "traefik.http.routers.spark-course.entrypoints=websecure"
        - "traefik.http.routers.spark-course.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.spark-course.loadbalancer.server.port=3001"
        - "traefik.http.routers.spark-course-api.rule=Host(`community.iacas.top`) && PathPrefix(`/api`)"
        - "traefik.http.routers.spark-course-api.entrypoints=websecure"
        - "traefik.http.routers.spark-course-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.spark-course-api.loadbalancer.server.port=3001"
        - "traefik.docker.network=network_public"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  network_public:
    external: true
    name: network_public 