version: '3.8'

services:
  app:
    image: automacaodebaixocusto/spark-course-unificado:v1.0.10
    environment:
      - JWT_SECRET=Q2h5b3VldG9zZWNyZXRzZXJhbGhhZG9yYWRvcmFuZG9tMTIzIT8kKiYoKS0r
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=community
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=131489152850082175195580
      - MINIO_ENDPOINT=mp.iacas.top
      - MINIO_PORT=443
      - MINIO_ACCESS_KEY=1013141255245882
      - MINIO_SECRET_KEY=5420658821784955
      - MINIO_USE_SSL=true
      - MINIO_REGION=us-east-1
      - MINIO_BUCKET=community
      - MINIO_PUBLIC_URL=https://mp.iacas.top

        # Upload Settings
      - MINIO_UPLOAD_TIMEOUT=300000
      - MINIO_MAX_FILE_SIZE=104857600
      - MINIO_RETENTION_DAYS=365
      

      
      # Mercado Pago - Produção
      - MERCADOPAGO_ACCESS_TOKEN=APP_USR-1488140951727118-070422-02ff2a4006d414790201bb46abbfa8dc-1501873958
      - MERCADOPAGO_WEBHOOK_SECRET=dc9c5a9d10bddb31e1ffe73f330ff32288de25db6bd7c2188c35501f1c60a94c
      - MERCADOPAGO_NOTIFICATION_URL=https://community.iacas.top/api/webhooks/mercadopago
     
      # Mercado Pago Configuration
      - MERCADOPAGO_SUCCESS_URL=https://community.iacas.top/payment/success
      - MERCADOPAGO_FAILURE_URL=https://community.iacas.top/payment/failure
      - MERCADOPAGO_PENDING_URL=https://community.iacas.top/payment/pending
    networks:
      - network_public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.spark-course.rule=Host(`community.iacas.top`)"
        - "traefik.http.routers.spark-course.entrypoints=websecure"
        - "traefik.http.routers.spark-course.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.spark-course.loadbalancer.server.port=3001"
        - "traefik.docker.network=network_public"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  network_public:
    external: true
    name: network_public 