version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      # Token de acesso principal do Mercado Pago
      - MERCADOPAGO_ACCESS_TOKEN=APP_USR-xxxxxxxxxxxx
      
      # Chave secreta para validar webhooks - DEVE ser exatamente igual ao "Webhook secret" do painel do Mercado Pago
      - MERCADOPAGO_WEBHOOK_SECRET=WHK-xxxx-xxxx-xxxx-xxxx
      
      # URL pública do seu webhook - DEVE ser acessível pela internet
      - MERCADOPAGO_NOTIFICATION_URL=https://seu-dominio.com/api/webhooks/mercadopago
      
      # URLs de retorno após pagamento
      - PAYMENT_SUCCESS_URL=https://seu-dominio.com/payment/success
      - PAYMENT_FAILURE_URL=https://seu-dominio.com/payment/failure
      - PAYMENT_CANCEL_URL=https://seu-dominio.com/payment/pending
      
      # URL base da sua aplicação
      - APP_URL=https://seu-dominio.com
      - NEXT_PUBLIC_APP_URL=https://seu-dominio.com
      
      # Configurações SMTP para recuperação de senha
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=seu-email@gmail.com
      - SMTP_PASS=sua-senha-de-app
      - SMTP_FROM=seu-email@gmail.com
      
      # Configurações do banco de dados
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spark_course
      
      # Chave secreta para JWT
      - JWT_SECRET=sua-chave-secreta-super-segura-aqui
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 